import { Listing, Application, Conversation, Message, UserProfile, Review } from '../types/database';

export const MOCK_USERS: UserProfile[] = [
  {
    id: '1',
    display_name: 'Marie Dupont',
    avatar_url: null,
    bio: 'Passionnée de jardinage et de cuisine. J\'adore aider mes voisins !',
    skills: ['Jardinage', 'Cuisine', 'Ménage'],
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    display_name: 'Thomas Martin',
    avatar_url: null,
    bio: 'Bricoleur du dimanche, toujours prêt à donner un coup de main.',
    skills: ['Bricolage', 'Déménagement', 'Informatique'],
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2024-02-01T10:00:00Z',
  },
  {
    id: '3',
    display_name: 'Sophie Bernard',
    avatar_url: null,
    bio: 'Étudiante en informatique, j\'aide pour les problèmes tech !',
    skills: ['Informatique', 'Courses'],
    created_at: '2024-03-10T10:00:00Z',
    updated_at: '2024-03-10T10:00:00Z',
  },
  {
    id: '4',
    display_name: 'Lucas Petit',
    avatar_url: null,
    bio: 'Sportif et motivé, je suis dispo pour les tâches physiques.',
    skills: ['Déménagement', 'Événement', 'Jardinage'],
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2024-04-01T10:00:00Z',
  },
];

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    user_id: '1',
    title: 'Aide pour tailler les haies du jardin',
    description: 'Bonjour ! J\'aurais besoin d\'un coup de main pour tailler les haies de mon jardin. C\'est un jardin de taille moyenne, environ 50m de haies. Je fournis les outils ! Un goûter sera offert pour remercier les bénévoles.',
    category: 'jardinage',
    address: '12 Rue des Lilas',
    city: 'Lyon',
    postal_code: '69003',
    latitude: 45.7578,
    longitude: 4.8320,
    preferred_date: '2026-03-05T09:00:00Z',
    estimated_duration: 3,
    spots_total: 2,
    spots_filled: 0,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-20T10:00:00Z',
    expires_at: '2026-03-20T10:00:00Z',
    user: MOCK_USERS[0],
  },
  {
    id: '2',
    user_id: '2',
    title: 'Déménagement studio → T2 même quartier',
    description: 'Je déménage d\'un studio au 3ème sans ascenseur vers un T2 au RDC, à 500m. Principalement des cartons + un canapé + un lit. Besoin de bras motivés ! Pizza et boissons offertes après.',
    category: 'demenagement',
    address: '8 Avenue Jean Jaurès',
    city: 'Paris',
    postal_code: '75019',
    latitude: 48.8792,
    longitude: 2.3829,
    preferred_date: '2026-03-01T08:00:00Z',
    estimated_duration: 4,
    spots_total: 4,
    spots_filled: 1,
    photos: [],
    is_urgent: true,
    status: 'active',
    created_at: '2026-02-22T14:00:00Z',
    expires_at: '2026-03-22T14:00:00Z',
    user: MOCK_USERS[1],
  },
  {
    id: '3',
    user_id: '3',
    title: 'Installation imprimante et WiFi chez ma grand-mère',
    description: 'Ma grand-mère a besoin d\'aide pour configurer sa nouvelle imprimante et connecter son ordinateur au WiFi. Elle habite seule et n\'est pas très à l\'aise avec la technologie.',
    category: 'informatique',
    address: '45 Boulevard Gambetta',
    city: 'Bordeaux',
    postal_code: '33000',
    latitude: 44.8378,
    longitude: -0.5792,
    preferred_date: '2026-03-08T14:00:00Z',
    estimated_duration: 1,
    spots_total: 1,
    spots_filled: 0,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-23T09:00:00Z',
    expires_at: '2026-03-23T09:00:00Z',
    user: MOCK_USERS[2],
  },
  {
    id: '4',
    user_id: '4',
    title: 'Aide pour organiser une fête de quartier',
    description: 'On organise une fête de quartier le week-end prochain ! Besoin d\'aide pour installer les tables, chaises, décoration et gérer le barbecue. Ambiance garantie !',
    category: 'evenement',
    address: '3 Place de la Mairie',
    city: 'Marseille',
    postal_code: '13001',
    latitude: 43.2965,
    longitude: 5.3698,
    preferred_date: '2026-03-10T10:00:00Z',
    estimated_duration: 8,
    spots_total: 6,
    spots_filled: 2,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-21T16:00:00Z',
    expires_at: '2026-03-21T16:00:00Z',
    user: MOCK_USERS[3],
  },
  {
    id: '5',
    user_id: '1',
    title: 'Courses pour personne à mobilité réduite',
    description: 'Je cherche quelqu\'un pour faire les courses hebdomadaires pour Mme Martin, qui a du mal à se déplacer. Liste fournie, supermarché à 5 min à pied.',
    category: 'courses',
    address: '22 Rue de la Paix',
    city: 'Lyon',
    postal_code: '69006',
    latitude: 45.7679,
    longitude: 4.8502,
    preferred_date: '2026-03-03T10:00:00Z',
    estimated_duration: 2,
    spots_total: 1,
    spots_filled: 0,
    photos: [],
    is_urgent: true,
    status: 'active',
    created_at: '2026-02-24T08:00:00Z',
    expires_at: '2026-03-24T08:00:00Z',
    user: MOCK_USERS[0],
  },
  {
    id: '6',
    user_id: '2',
    title: 'Montage meuble IKEA (armoire PAX)',
    description: 'J\'ai acheté une armoire PAX chez IKEA et j\'ai besoin d\'aide pour le montage. J\'ai tous les outils mais c\'est plus facile à deux ! Prévoir environ 2-3h.',
    category: 'bricolage',
    address: '15 Rue du Commerce',
    city: 'Toulouse',
    postal_code: '31000',
    latitude: 43.6047,
    longitude: 1.4442,
    preferred_date: '2026-03-07T14:00:00Z',
    estimated_duration: 3,
    spots_total: 1,
    spots_filled: 0,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-19T11:00:00Z',
    expires_at: '2026-03-19T11:00:00Z',
    user: MOCK_USERS[1],
  },
  {
    id: '7',
    user_id: '3',
    title: 'Promenade de chien pendant mes vacances',
    description: 'Je pars en vacances du 5 au 12 mars. Cherche quelqu\'un pour promener mon labrador Max 2 fois par jour (matin et soir, 30min chaque). Il est très gentil !',
    category: 'animaux',
    address: '7 Allée des Cèdres',
    city: 'Nantes',
    postal_code: '44000',
    latitude: 47.2184,
    longitude: -1.5536,
    preferred_date: '2026-03-05T08:00:00Z',
    estimated_duration: 1,
    spots_total: 1,
    spots_filled: 0,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-18T15:00:00Z',
    expires_at: '2026-03-18T15:00:00Z',
    user: MOCK_USERS[2],
  },
  {
    id: '8',
    user_id: '4',
    title: 'Grand ménage de printemps appartement',
    description: 'Besoin d\'aide pour un grand ménage de printemps dans mon appartement T3. Nettoyage en profondeur : vitres, sols, cuisine, salle de bain. Je fournis tous les produits !',
    category: 'menage',
    address: '30 Rue Nationale',
    city: 'Lille',
    postal_code: '59000',
    latitude: 50.6292,
    longitude: 3.0573,
    preferred_date: '2026-03-15T09:00:00Z',
    estimated_duration: 4,
    spots_total: 2,
    spots_filled: 0,
    photos: [],
    is_urgent: false,
    status: 'active',
    created_at: '2026-02-17T12:00:00Z',
    expires_at: '2026-03-17T12:00:00Z',
    user: MOCK_USERS[3],
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: '1',
    listing_id: '2',
    other_user: MOCK_USERS[1],
    listing: MOCK_LISTINGS[1],
    last_message: 'Super, à samedi alors !',
    last_message_date: '2026-02-24T10:30:00Z',
    unread: 2,
  },
  {
    id: '2',
    listing_id: '1',
    other_user: MOCK_USERS[0],
    listing: MOCK_LISTINGS[0],
    last_message: 'Bonjour, est-ce que le créneau du matin vous convient ?',
    last_message_date: '2026-02-23T18:00:00Z',
    unread: 0,
  },
  {
    id: '3',
    listing_id: '4',
    other_user: MOCK_USERS[3],
    listing: MOCK_LISTINGS[3],
    last_message: 'Merci pour votre aide, c\'est vraiment gentil !',
    last_message_date: '2026-02-22T14:15:00Z',
    unread: 1,
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: '1',
    conversation_id: '1',
    sender_id: '2',
    content: 'Bonjour ! Je suis intéressé pour aider au déménagement samedi.',
    read_at: '2026-02-24T09:00:00Z',
    created_at: '2026-02-24T08:30:00Z',
  },
  {
    id: '2',
    conversation_id: '1',
    sender_id: 'me',
    content: 'Génial ! On commence à 8h, ça te va ?',
    read_at: '2026-02-24T09:30:00Z',
    created_at: '2026-02-24T09:15:00Z',
  },
  {
    id: '3',
    conversation_id: '1',
    sender_id: '2',
    content: 'Parfait, je serai là. Tu as besoin qu\'on apporte quelque chose ?',
    read_at: '2026-02-24T10:00:00Z',
    created_at: '2026-02-24T09:45:00Z',
  },
  {
    id: '4',
    conversation_id: '1',
    sender_id: 'me',
    content: 'Non c\'est bon, j\'ai tout prévu. Juste des bras solides 💪',
    read_at: '2026-02-24T10:15:00Z',
    created_at: '2026-02-24T10:00:00Z',
  },
  {
    id: '5',
    conversation_id: '1',
    sender_id: '2',
    content: 'Super, à samedi alors !',
    read_at: null,
    created_at: '2026-02-24T10:30:00Z',
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: '1',
    listing_id: '2',
    user_id: 'me',
    status: 'accepted',
    created_at: '2026-02-23T10:00:00Z',
    listing: MOCK_LISTINGS[1],
  },
  {
    id: '2',
    listing_id: '4',
    user_id: 'me',
    status: 'pending',
    created_at: '2026-02-22T14:00:00Z',
    listing: MOCK_LISTINGS[3],
  },
  {
    id: '3',
    listing_id: '7',
    user_id: 'me',
    status: 'rejected',
    created_at: '2026-02-20T09:00:00Z',
    listing: MOCK_LISTINGS[6],
  },
];
